#!/usr/bin/env python3

import sys
import json
import os.path
import requests
import configparser

config_path = os.path.expanduser('~/.gerrit-webhook')

config = configparser.RawConfigParser()
config.read(config_path)

url = config.get('webhook', 'url')

def fire_webhook(payload):
    headers = {'content-type': 'application/json'}
    requests.post(url, data=json.dumps(payload), headers=headers)
    
def main():
    if len(sys.argv) < 2:
        exit()
        
    payload = {}
    opts = sys.argv[1:]
    for i in range(int(len(opts)/2)):
        payload.update({opts[i*2][2:]: opts[i*2+1]})
        
    fire_webhook(payload)
    
if __name__ == '__main__':
    main()
